baseURL = "/"
languageCode = "en-US"
contentDir = "content"

[module]
    # uncomment line below for temporary local development of module,
    # when using a 'theme' as a git submodule or git cloned files
    # replacements = "github.com/colinwilson/lotusdocs -> lotusdocs"
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false
    
defaultContentLanguage = 'en'
[languages]
    [languages.en]
        title = "Lotus Docs Example Site"
        languageName = "English"
        weight = 10
    [languages.pt]
        title = "Lotus Docs Exemple de Site"
        languageName = "Poruguês"
        contentDir = "content/pt"
        weight = 20

[params]
    google_fonts = [
        ["Inter", "300, 400, 600, 700"],
        ["Fira Code", "400, 700"]
    ]
    sans_serif_font = "Inter"
    secondary_font = "Inter"
    mono_font = "Fira Code"

[params.docs]
    title = "Building a Technical Documentation Website"
    darkMode = true # enable dark mode option? default false
    themeColor = "cyan"
    titleIcon = true
    sidebarIcons = true
    prism = true
    prismTheme = "lucario"
    
[menu]
[[menu.primary]]
    name  = "Docs"
    url = "docs/"
    identifier = "docs"
    weight = 10
